config/routes.rb
Rails.application.routes.draw do
   root 'home#index'
   # 用户资源使用特殊的 resources 方法自动获得符合 REST 架构的路由
  resources :users
  get  '/signup',  to: 'users#new'
  # 创建新会话的页面（登录）, HTTP请求GET, URL: /login, 具名路由: login_path, 动作:new
  get '/login', to: 'sessions#new'

  #创建新会话（登录）,HTTP请求POST, URL: /login, 具名路由: login_path, 动作:create
  post '/login', to: 'sessions#create'
  
  # 删除会话（退出）, HTTP请求DELETE, URL: /logout, 具名路由: logout_path, 动作:destroy
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  #挂上 image uploader
mount_uploader :image, ImageUploader
attr_accessor :remember_token
before_save { self.email = email.downcase }

 # 用户名不能为空， 长度至少为4
 validates :name, presence: true, length: { minimum: 4 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

# (验证邮箱是否存在，长度，格式，唯一性，不区分大小写)
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
 
 has_secure_password
 # 密码不能为空，是含有小写字母、大写字母、数字、特殊符号，长度至少为8,更新时允许密码为空
 validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

# 返回指定字符串的哈希摘要
def User.digest(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
  BCrypt::Password.create(string, cost: cost)
end

 #记住用户的登录状态要创建一个记忆令牌，并且在数据库中存储这个令牌的摘要, 返回一个随机令牌
def User.new_token
  SecureRandom.urlsafe_base64  
end

 # 为了持久会话，在数据库中记住用户
def remember
  self.remember_token = User.new_token 
  update_attribute(:remember_digest, User.digest(remember_token))  
end

 # 如果指定的令牌和摘要匹配，返回 true
def authenticated?(remember_token)
  return false if remember_digest.nil? 
  BCrypt::Password.new(remember_digest).is_password?(remember_token)  
end

 # 忘记用户
def forget
  update_attribute(:remember_digest, nil)  
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  #登入用户
  def create
    # 提交表单后会生成 params 个嵌套哈希，电子邮件地址和密码都在 :session 键中
    # Active Record 提供的 User.find_by方法和 has_secure_password 提供的 authenticate 方法,
    # 如果认证失败，authenticate 方法会返回 false
    # 电子邮件地址都是以小写字母形式保存的，所以这里调用了 downcase 方法
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user 
      remember user #登录并记住登录状态
      redirect_to user #用户登录成功就使用该方法记住该用户,然后重定向到用户的资料页面
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end 
  end
  
  # 退出登陆
  def destroy
    log_out if logged_in? 
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :correct_user,  only: [:edit, :update]
  # before_action :logged_in_user, only: [:edit, :update]

  def index
    @users = User.all  
  end

  def new
    @user = User.new
  end
  
  def show
     @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      #注册的过程中自动登入用户,调用 log_in 方法
    log_in @user 
    flash[:success] = "create successful"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])  
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params) # 处理更新成功的情况
      flash[:success] = "Profile updated" 
      redirect_to @user
     else render 'edit'    
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,:image)
  end

  # def logged_in_user
  #   unless logged_in? flash[:danger] = "Please log in." 
  #     redirect_to login_url 
  #   end    
  # end

  # def correct_user
  #   @user = User.find(params[:id]) 
  #   redirect_to(root_url) 
  #    unless @user == current_user    
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 登入指定的用户,session 方法协助,session 视作一个哈希进行赋值，
  # 用户的浏览器中创建一个临时 cookie，内容是加密后的用户 ID。在后续的请求中，可以使用 session[:user_id] 取回这个 ID，浏览器关闭后立即失效，
  # 想在多个不同的地方使用这个登录方式，所以在这里辅助方法模块中定义一个名为 log_in 的方法。
  # session 方法创建的临时 cookie 会自动加密，攻击者无法使用会话中的信息以该用户的身份登录，但这只是针对临时 cookie。
  def log_in(user)
    session[:user_id] = user.id
  end

  # 在持久登陆中记住用户，在浏览器中存储了有效的记忆令牌
  def remember(user)
    user.remember 
    cookies.permanent.signed[:user_id] = user.id 
    cookies.permanent[:remember_token] = user.remember_token  
  end

   #忘记登陆
  def forget(user)
    user.forget 
    cookies.delete(:user_id) 
    cookies.delete(:remember_token)  
  end

   # 退出当前用户
   # log_out 方法放在辅助方法模块中
  def log_out
    forget(current_user) 
    session.delete(:user_id) 
    @current_user = nil
  end
  
  #如果用户 ID 不存在，find 方法会抛出异常。在用户的资料页面可以使用这种表现，因为必须有相应的用户才能显示他的信息。
  #但 session[:user_id] 的值经常是 nil（表示用户未登录),所以通过 id 查找用户
  #把 User.find_by 的结果存储在实例变量中，只在第一次调用时查询数据库，后续再调用直接返回实例变量中存储的值
  # ||=（或等）赋值操作符，如果变量的值为 nil 则给它赋值，否则就不改变这个变量的值
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id]) 
        user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # 如果用户已登录，返回 true，否则返回 false
  # 检测有没有当前用户要使用“非”操作符 !
  def logged_in?
    !current_user.nil?
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_error_messages.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">
        
Design by yourname
        
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">YOUCOURSE </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Category",   '#' %></li>
                <li><%= link_to "Locations",   '#' %></li>
               <% if logged_in? %>
                   <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.name %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <%# 跳转到个人信息页 %>
                        <li><%= link_to "view Profile", current_user %></li>
                        <%# 跳转到编辑用户页 %>
                        <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li>
                          <%= link_to "Log out", logout_path, method: "delete" %>
                        </li>
                    </ul>
                  </li>
                <% else %>
                    <li><%= link_to("Log in", login_path) %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<div class="jumbotron bg-1 text-center">
   <h2 class="title" style="color:white">Welcome to Your Course App</h2>
   <p  class="slogan">this is the home page for the RAD Assignment 2</p>
  <br>
  <br>
   <p class="lead"><%= link_to("Sign up now!", signup_path, class: "btn btn-lg btn-danger") %>
   </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YOUCOURSE</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

     <%= render "common/footer" %>
  </body>
</html>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user) do |f| %>
  <%= render 'common/error_messages' %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <% if @user.image.present? %>
    <span>image</span> 
    <%= image_tag(@user.image.thumb.url) %>
  <% end %>

  <%= f.label :password %>
  <%= f.file_field :image, as: :file %>

  <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>

 <%# <div class="gravatar_edit">
   <%= gravatar_for @user %>
   <%# <a href="http://gravatar.com/emails" target="_blank">change</a>
 </div> %>
 </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
 <li>
  <%# <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
 </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Coordinator Register') %>
<div class="col-md-6 col-md-offset-4"><h1>Coordinator Register</h1>
<hr style="FILTER: alpha(opacity=100,finishopacity=0,style=3)" width="80%" color=#987cb9 SIZE=3>
</div>
<div class="row">
  <div class="jumbotron bg-1 col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'common/error_messages' %>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
          <%= f.label :image %>
          <%= f.file_field :image, as: :file %>
      <span class="col-md-8 col-md-offset-4"><%= f.submit "Register", class: "btn btn-primary" %></span>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= current_user.name %>, <%= current_user.email %>,<%= image_tag(current_user.image.thumb.url) %>